url: https://whispersystems.org
safe: false
auto: true
pygments: true
assets:
  js_compressor:  uglifier
  css_compressor: sass
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
  - Makefile
  - README.md
  - vendor
  - Rakefile
permalink: /blog/:title/
sass:
    style:  expanded  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory
